services:
  cam:
    build: .
    restart: unless-stopped
    devices: 
      - "/dev/ttyACM0:/dev/ttyACM0"
    ports:
      - "5001:5001"
    network_mode: "host"
    cpus: "2"
    mem_limit: "512m"

